"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Bot, Check, ChevronRight, Globe2, Layers3, Orbit, Sparkles, Zap } from "lucide-react";
import { Panel } from "@fliptrybe/ui";
import { type Capability, marketplaceHighlights, networks, pillars } from "./data";
import { MarketingFooter } from "./footer";
import { MarketingNavigation } from "./navigation";

function Fade({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const reduce = useReducedMotion();
  return <motion.div initial={{ opacity: 0, y: reduce ? 0 : 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-70px" }} transition={{ duration: 0.65, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}

function Status({ status }: { status: Capability["status"] }) {
  const label = status === "live" ? "Live" : status === "selected-markets" ? "Selected markets" : status === "early-access" ? "Early access" : "Coming soon";
  return <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--ft-border)] bg-[var(--ft-bg-muted)] px-2.5 py-1 font-mono text-[9px] font-semibold uppercase tracking-[0.14em] text-[var(--ft-text-muted)]"><span className="size-1.5 rounded-full bg-current" />{label}</span>;
}

function CapabilityTile({ capability }: { capability: Capability }) {
  return <Panel className="group relative overflow-hidden p-5 transition duration-300 hover:-translate-y-1 hover:border-[var(--ft-accent)]/40 hover:shadow-[var(--shadow-lg)]"><div className="pointer-events-none absolute -right-10 -top-10 size-28 rounded-full bg-[var(--ft-accent-glow)] blur-3xl opacity-0 transition group-hover:opacity-100" /><div className="relative flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-muted)] text-[var(--ft-accent)]"><capability.icon className="size-5" /></span><Status status={capability.status} /></div><h3 className="mt-5 text-sm font-semibold tracking-tight">{capability.title}</h3><p className="mt-2 text-xs leading-5 text-[var(--ft-text-secondary)]">{capability.description}</p></Panel>;
}

export function FliptribeHomepage() {
  return <main id="top" className="min-h-screen overflow-x-hidden bg-[var(--ft-bg-base)] text-[var(--ft-text-primary)]" style={{ backgroundImage: "var(--ft-bg-page-gradient)" }}>
    <MarketingNavigation />
    <section className="relative px-4 pb-20 pt-36 sm:px-6 sm:pb-28 sm:pt-40 lg:pt-44"><div className="ft-grid-bg pointer-events-none absolute inset-x-0 top-20 h-[620px] opacity-40" /><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1fr_0.92fr]">
      <div className="relative z-10"><Fade><div className="inline-flex items-center gap-2 rounded-full border border-[var(--ft-border)] bg-[var(--ft-bg-surface)] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--ft-text-secondary)] shadow-[var(--shadow-sm)] backdrop-blur-xl"><Sparkles className="size-3.5 text-[var(--ft-accent)]" /> FlipTrybe Technology</div></Fade><Fade delay={0.08}><h1 className="mt-7 max-w-4xl text-balance font-[var(--font-display)] text-5xl font-semibold leading-[0.96] tracking-[-0.055em] sm:text-6xl lg:text-[76px]">One intelligent layer for how the world <span className="bg-gradient-to-r from-[var(--ft-accent)] to-[var(--ft-accent-2)] bg-clip-text text-transparent">moves, pays and grows.</span></h1></Fade><Fade delay={0.16}><p className="mt-7 max-w-2xl text-base leading-7 text-[var(--ft-text-secondary)] sm:text-lg sm:leading-8">FlipTrybe Technology brings money movement, digital services, commerce, advertising and growth infrastructure into one connected operating system for people and businesses.</p></Fade><Fade delay={0.24}><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/register" className="group inline-flex h-13 items-center justify-center gap-2 rounded-full bg-[var(--ft-text-primary)] px-6 text-sm font-semibold text-[var(--ft-text-inverse)] shadow-[var(--shadow-lg)] transition hover:-translate-y-0.5">Enter the platform <ArrowRight className="size-4 transition group-hover:translate-x-1" /></a><a href="#platform" className="inline-flex h-13 items-center justify-center gap-2 rounded-full border border-[var(--ft-border-strong)] bg-[var(--ft-bg-surface)] px-6 text-sm font-semibold backdrop-blur-xl transition hover:border-[var(--ft-accent)]">Explore the system <ChevronRight className="size-4" /></a></div></Fade><Fade delay={0.3}><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-[11px] text-[var(--ft-text-muted)]">{["One account", "Real-time controls", "Built for Africa, designed for everywhere"].map(item => <span key={item} className="inline-flex items-center gap-2"><Check className="size-3.5 text-[var(--ft-green)]" />{item}</span>)}</div></Fade></div>
      <Fade delay={0.12}><div className="relative mx-auto w-full max-w-xl"><div className="pointer-events-none absolute -inset-8 rounded-[48px] bg-[radial-gradient(circle_at_25%_20%,var(--ft-accent-glow),transparent_38%),radial-gradient(circle_at_82%_70%,var(--ft-accent-2-glow),transparent_42%)] blur-2xl" /><div className="ft-glass relative overflow-hidden rounded-[30px] border border-[var(--ft-border-strong)] p-4 shadow-[var(--shadow-xl)]"><div className="flex items-center justify-between rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-muted)]/60 px-4 py-3"><div className="flex items-center gap-3"><img alt="" className="size-8" src="/brand/icon-mark.svg" /><div><div className="text-xs font-semibold">FlipTrybe OS</div><div className="font-mono text-[9px] uppercase tracking-[0.18em] text-[var(--ft-text-muted)]">Control surface</div></div></div><div className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-[var(--ft-green)]" /><span className="font-mono text-[9px] uppercase tracking-[0.15em] text-[var(--ft-text-muted)]">Systems online</span></div></div><div className="mt-3 grid gap-3 sm:grid-cols-[1.25fr_0.75fr]"><div className="rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-raised)] p-5"><div className="flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-[var(--ft-text-muted)]">Operating balance</span><Globe2 className="size-4 text-[var(--ft-accent)]" /></div><div className="mt-5 font-[var(--font-display)] text-4xl font-semibold tracking-[-0.04em]">₦1.48m</div><div className="mt-1 text-xs text-[var(--ft-text-secondary)]">Protected operating balance</div><div className="mt-6 h-20 overflow-hidden rounded-xl bg-[var(--ft-accent-subtle)] p-2"><svg viewBox="0 0 400 72" className="h-full w-full"><path d="M0 60 C40 42,65 50,95 36 S155 48,190 25 S255 32,290 18 S345 22,400 6" fill="none" stroke="currentColor" strokeWidth="3" className="text-[var(--ft-accent)]" /></svg></div></div><div className="grid gap-3">{[["Services","24",Layers3],["Markets","18",Globe2],["Automations","07",Bot]].map(([label,value,Icon]) => { const IconComponent = Icon as typeof Layers3; return <div key={String(label)} className="rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-raised)] p-4"><IconComponent className="size-4 text-[var(--ft-accent-2)]"/><div className="mt-5 font-[var(--font-display)] text-2xl font-semibold">{String(value)}</div><div className="mt-1 text-[11px] text-[var(--ft-text-muted)]">{String(label)}</div></div>})}</div></div><div className="mt-3 grid grid-cols-3 gap-3">{[["Money","Active"],["Services","Ready"],["Growth","Scaling"]].map(([a,b]) => <div key={a} className="rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-raised)] p-4"><div className="text-xs font-semibold">{a}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.12em] text-[var(--ft-green)]">{b}</div></div>)}</div></div></div></Fade>
    </div></section>

    <section className="border-y border-[var(--ft-border)] bg-[var(--ft-bg-surface)]/55 px-4 py-5 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 text-xs text-[var(--ft-text-muted)]"><span className="font-mono uppercase tracking-[0.18em]">Connected infrastructure</span><div className="flex flex-wrap items-center gap-5 font-medium">{networks.slice(0, 8).map(network => <span key={network}>{network}</span>)}</div></div></section>

    <section id="platform" className="px-4 py-24 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><Fade><div className="max-w-3xl"><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[var(--ft-accent)]">The platform</span><h2 className="mt-4 font-[var(--font-display)] text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Infrastructure that behaves like one product.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--ft-text-secondary)]">Every layer shares identity, money, service state, insights and controls instead of acting like a collection of unrelated tools.</p></div></Fade><div className="mt-12 grid gap-5 lg:grid-cols-3">{pillars.map((pillar,index) => <Fade delay={index*0.08} key={pillar.id}><div className="rounded-[28px] border border-[var(--ft-border)] bg-[var(--ft-bg-surface)] p-5 shadow-[var(--shadow-md)]"><div className="flex items-center justify-between"><div className="font-mono text-[9px] font-semibold uppercase tracking-[0.2em] text-[var(--ft-accent)]">0{index+1}</div><Orbit className="size-4 text-[var(--ft-text-muted)]"/></div><h3 className="mt-10 text-xl font-semibold tracking-tight">{pillar.headline}</h3><p className="mt-2 text-sm leading-6 text-[var(--ft-text-secondary)]">{pillar.blurb}</p><div className="mt-6 grid gap-2">{pillar.capabilities.slice(0,4).map(cap => <div className="flex items-center justify-between rounded-xl border border-[var(--ft-border)] bg-[var(--ft-bg-raised)] px-3 py-2.5" key={cap.title}><span className="flex items-center gap-2 text-xs font-medium"><cap.icon className="size-3.5 text-[var(--ft-accent)]" />{cap.title}</span><Status status={cap.status}/></div>)}</div><a className="mt-6 inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--ft-accent)]" href={pillar.href}>{pillar.ctaLabel}<ArrowRight className="size-3.5"/></a></div></Fade>)}</div></div></section>

    <section className="border-y border-[var(--ft-border)] px-4 py-24 sm:px-6 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><Fade><div><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[var(--ft-accent-2)]">The intelligence layer</span><h2 className="mt-4 font-[var(--font-display)] text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Make the next move before it becomes the obvious one.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[var(--ft-text-secondary)]">AI-assisted campaign operations, service selection, performance signals and operational alerts sit on top of the same system of record.</p><a href="/register" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[var(--ft-accent)] px-5 py-3 text-sm font-semibold text-white shadow-[var(--shadow-md)]">Build your operating layer <ArrowRight className="size-4"/></a></div></Fade><Fade delay={0.08}><div className="relative overflow-hidden rounded-[30px] border border-[var(--ft-border-strong)] bg-[var(--ft-bg-raised)] p-5 shadow-[var(--shadow-xl)]"><div className="absolute right-0 top-0 size-60 rounded-full bg-[var(--ft-accent-2-glow)] blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[0.18em] text-[var(--ft-text-muted)]">Signal engine</div><div className="mt-1 text-lg font-semibold">Growth intelligence</div></div><Bot className="size-5 text-[var(--ft-accent-2)]"/></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-muted)] p-4"><div className="text-xs text-[var(--ft-text-muted)]">Opportunity score</div><div className="mt-2 font-[var(--font-display)] text-4xl font-semibold">92</div><div className="mt-1 text-xs text-[var(--ft-green)]">High-confidence window</div></div><div className="rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-muted)] p-4"><div className="text-xs text-[var(--ft-text-muted)]">Suggested action</div><div className="mt-2 text-sm font-semibold">Shift budget to the best-performing creative cluster.</div></div></div><div className="mt-3 rounded-2xl border border-[var(--ft-border)] bg-[var(--ft-bg-muted)] p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold">Recommendation confidence</span><span className="font-mono text-xs text-[var(--ft-green)]">97.2%</span></div><div className="mt-3 h-2 rounded-full bg-[var(--ft-bg-sunken)]"><div className="h-full w-[97%] rounded-full bg-gradient-to-r from-[var(--ft-accent)] to-[var(--ft-accent-2)]"/></div></div></div></div></Fade></div></section>

    <section className="px-4 py-24 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><Fade><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[var(--ft-accent)]">Built for real work</span><h2 className="mt-4 font-[var(--font-display)] text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">From one payment to an entire growth operation.</h2></div><a href="/register" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--ft-accent)]">Create an account <ArrowRight className="size-4"/></a></div></Fade><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{marketplaceHighlights.map((item,index) => <Fade delay={index*0.05} key={item.label}><Panel className="h-full p-5"><div className="grid size-11 place-items-center rounded-2xl bg-[var(--ft-accent-subtle)] text-[var(--ft-accent)]"><item.icon className="size-5"/></div><div className="mt-6 text-sm font-semibold">{item.label}</div><div className="mt-2 text-xs leading-5 text-[var(--ft-text-secondary)]">Designed to connect into the same operating layer.</div></Panel></Fade>)}</div></div></section>

    <section className="px-4 pb-24 sm:px-6 sm:pb-32"><Fade><div className="mx-auto max-w-7xl overflow-hidden rounded-[32px] border border-[var(--ft-border-strong)] bg-[radial-gradient(circle_at_10%_0%,var(--ft-accent-glow),transparent_34%),radial-gradient(circle_at_90%_100%,var(--ft-accent-2-glow),transparent_34%),var(--ft-bg-raised)] p-8 shadow-[var(--shadow-xl)] sm:p-12 lg:p-16"><div className="max-w-3xl"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.22em] text-[var(--ft-accent)]"><Zap className="size-3.5"/> Next-generation infrastructure</div><h2 className="mt-5 font-[var(--font-display)] text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">The future will feel normal once the infrastructure is invisible.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--ft-text-secondary)]">That is the standard for FlipTrybe Technology: fewer seams, clearer decisions and a platform that gets more capable without getting harder to use.</p><a href="/register" className="mt-8 inline-flex items-center justify-center gap-2 rounded-full bg-[var(--ft-text-primary)] px-6 py-3.5 text-sm font-semibold text-[var(--ft-text-inverse)]">Start with FlipTrybe <ArrowRight className="size-4"/></a></div></div></Fade></section>
    <MarketingFooter />
  </main>;
}
