-- Phase 4: Enable RLS for internal infrastructure, audit, provider, webhook, validation, and admin-only tables.
-- No Supabase client policies are added. These tables remain backend service-role only.

ALTER TABLE IF EXISTS public."EventOutbox" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ProviderConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ProviderHealth" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ProviderRoutingAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."FxRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."FxRateCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."FxQuote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SettlementInstruction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SettlementReconciliation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SettlementWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ProviderWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PricingRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VtuProviderRoute" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VirtualNumberMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NumberCompatibility" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VirtualNumberPurchaseLimit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VirtualNumberReconciliation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VirtualNumberMarginAnalytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NotificationDeliveryAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."OutgoingWebhookSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."OutgoingWebhookDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RewardFulfillment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VerificationEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SubmissionSecret" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ValidationRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StageResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Signal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."OcrResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ImageQualityResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."BrandRuleSet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ModerationQueue" ENABLE ROW LEVEL SECURITY;
